In [247]:
import pandas as pd
import numpy as np

In [248]:
df = pd.DataFrame(
    [[4,8,12],
     [5,9,13],
     [6,10,14],
     [7,11,15]],
    columns=['a','b','c']
)
df[['a','b','c']]

   a   b   c
0  4   8  12
1  5   9  13
2  6  10  14
3  7  11  15

In [249]:
# print(df)

In [250]:
# df = pd.DataFrame(
# [[4, 7, 10],
# [5, 8, 11],
# [6, 9, 12]],
# index=[1, 2, 3],
# columns=['a', 'b', 'c'])

In [251]:
# df = pd.DataFrame(
# {"a" : [4 ,5, 6],
# "b" : [7, 8, 9],
# "c" : [10, 11, 12]}, index = pd.MultiIndex.from_tuples(
# [('d', 1), ('d', 2), ('e', 2)], names=['n', 'v']))

In [252]:
# df.sort_values('a')
# df.sort_values('a', ascending=False)
# df.rename(columns={'a':'Age'}, inplace=True)
# df.reset_index()
# df.drop(columns=['b'])
# df

In [253]:
df = df.assign(total=lambda x: x.a + x.c)

In [254]:
df

   a   b   c  total
0  4   8  12     16
1  5   9  13     18
2  6  10  14     20
3  7  11  15     22

In [255]:
df1 = pd.DataFrame(
    [[4,7,10],
     [15,18,111],
     [16,19,112]],
    columns=['id','b','c']
)
df2 = pd.DataFrame(
    [[4,7,10],
     [25,28,211],
     [26,29,212]],
    columns=['id2','b','c']
)

In [256]:
# pd.merge(df1, df2, how='inner', on='id')
# pd.merge(df1, df2, how='left', on='id')
pd.merge(df1, df2, how='right', right_on='id2', left_on='id')

# pd.merge(df1, df2, how='outer' , right_on='id2', left_on='id')

    id  b_x   c_x  id2  b_y  c_y
0  4.0  7.0  10.0    4    7   10
1  NaN  NaN   NaN   25   28  211
2  NaN  NaN   NaN   26   29  212

In [257]:
# pd.melt(df)
# df.pivot(columns='a', values='val')
# pd.concat([df1, df2])

In [258]:
# df2 = pd.DataFrame({
#     'name': ['Ali', 'Ali', 'Sara', 'Sara'],
#     'subject': ['math', 'english', 'math', 'english'],
#     'score': [90, 88, 85, 92]
# })
# df2

In [259]:
# df_wide = df2.pivot(index='name', columns='subject', values='score')
# print(df_wide)

In [260]:
df

   a   b   c  total
0  4   8  12     16
1  5   9  13     18
2  6  10  14     20
3  7  11  15     22

In [261]:
df[['a','b']].expanding( min_periods=1).sum()

      a     b
0   4.0   8.0
1   9.0  17.0
2  15.0  27.0
3  22.0  38.0

In [262]:
pd.concat([df1, df2], axis=1)

   id   b    c  id2   b    c
0   4   7   10    4   7   10
1  15  18  111   25  28  211
2  16  19  112   26  29  212

In [269]:
import pandas as pd

# 1. إنشاء جدول الطلاب المسجلين (ydf)
ydf = pd.DataFrame({
    'student_id': [101, 102, 103, 104],
    'name': ['Ali', 'Sara', 'Omar', 'Huda']
})

# 2. إنشاء جدول الطلاب الذين حضروا الامتحان (zdf)
zdf = pd.DataFrame({
    'student_id': [102, 104],
    'score': [85, 92]
})

# 3. تطبيق العملية لاستخراج "الغائبين" (الموجودين في ydf وليس zdf)
absentees = pd.merge(ydf, zdf, on='student_id', how='outer', indicator=True) \
              .query('_merge == "left_only"') \
              .drop(columns=['_merge'])

print("الطلاب الذين سجلوا ولم يحضروا الامتحان:")
print(absentees)

الطلاب الذين سجلوا ولم يحضروا الامتحان:
   student_id  name  score
0         101   Ali    NaN
2         103  Omar    NaN